[package]
name = "suha"
version = "0.1.0"
edition = "2018"

[dependencies]
crossbeam-channel = "0.5.1"
crossterm = "0.20.0"
tui = { version = "0.15.0", default-features = false, features = ["crossterm"] }
unicode-width = "0.1.8"
