[package]
name = "suha"
version = "0.1.0"
edition = "2018"

[dependencies]
crossbeam-channel = "0.5.1"
crossterm = "0.20.0"
phf = { version = "0.9.0", features = ["macros"] }
tui = "0.15.0"
termion = "1.5.6"
unicode-width = "0.1.8"
